### ISSUE TITLE
Feature Request: Please add rule for scx (sched-ext)

### ISSUE THREAD

**Issue by ajdgsu** [CachyOS/ananicy-rules#126]
The scx programs are part of the sched-ext kernel scheduling program. Because of sched-ext schedulers are running in user space environmemt, so it's nessary to set a higher priority.

The scx programs are come with scx_xxx (xxx is the schedulers name, like `scx_bpfland`)

For now CachyOS have these schedulers by default: `scx_bpfland scx_lavd scx_nest scx_rlfifo scx_rusty scx_userland scx_central scx_layered scx_qmap scx_rustland scx_simple`

**Comment by ajdgsu** [comment]
Actually what I mean is set the higher priority for scx schedulers itself. I'm not sure it's my problem or not, but my PC's scx program always randomly stopped when system have heavy load. After I manually set the higher priority for scx program, the problem just gone.

**Comment by ptr1337** [comment]
> Actually what I mean is set the higher priority for scx schedulers itself. I'm not sure it's my problem or not, but my PC's scx program always randomly stopped when system have heavy load. After I manually set the higher priority for scx program, the problem just gone.

Mhm, this seems very unlikely. Please make a report to the scx repostitory with logs and the crashes. Thanks
