### ISSUE TITLE
Feature Request: Sober (Roblox launcher)

### ISSUE THREAD

**Issue by nijahplays** [CachyOS/ananicy-rules#136]
Add Sober for Roblox

My rule I made:

`# Roblox game player: https://sober.vinegarhq.org/
{ "name": "sober", "type": "Game" }
`

**Comment by ptr1337** [comment]
Please make a PR

**Comment by nijahplays** [comment]
> Please make a PR

I don't know how to :/

**Comment by nijahplays** [comment]
Made a PR

https://github.com/CachyOS/ananicy-rules/pull/137

**Comment by nijahplays** [comment]
Merged https://github.com/CachyOS/ananicy-rules/pull/137
