### ISSUE TITLE
Attached spotube.rules for your review. (Apologies I know nothing about github and pr's).

### ISSUE THREAD

**Issue by famewolf** [CachyOS/ananicy-rules#140]
Spotube is an open source spotify music client.

File: spotube.rules in /etc/ananicy.d/00-default/Audio-Video

# Spotify Ltd. is a music streaming platform: https://www.spotify.com/download/linux/
# Spotube is an open source music client for Spotify.  https://github.com/KRTirtho/spotube
{ "name": "spotube", "type": "Player-Audio" }

**Comment by shvedes** [comment]
> Apologies I know nothing about github and pr's

1. Fork repo in the GitHub
2. Clone created fork to your machine
3. Do changes
4. Go to GitHub > Open your fork
5. Press on the button "Compare and Pull Request"

[Link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
