### ISSUE TITLE
Please provide releases

### ISSUE THREAD

**Issue by inglor** [CachyOS/ananicy-rules#148]
By tagging a release you can:
- sign it
- have a stable version while you work on issues on HEAD
- users have an idea of which version they are using when raising issues
- easier to package downstream

Please and thank you :)

**Comment by ptr1337** [comment]
Hi @inglor 

Thanks for the suggestion. I have just created the first release with the 1.0.0 as verison:
https://github.com/CachyOS/ananicy-rules/releases/tag/1.0.0

We will keep doing in the future releases, to track better regression and for easier packaging.
