### ISSUE TITLE
The rules are not applied automatically

### ISSUE THREAD

**Issue by Ssdj3nt** [CachyOS/ananicy-rules#161]
I noticed that at startup the ananicy-rules are not applied.

The ananicy-cpp.service is running, restarting the service can trigger its application, otherwise,

the rules are applied when i start a specific application, i noticed it with firefox.

I'm not sure if it's an ananicy-cpp bug or the rules.

https://github.com/user-attachments/assets/305529c1-b423-4b07-b2e2-205e45675380

**Comment by Shendisx** [comment]
Have you updated the ananicy-rules package? on 1.0.1 there was a broken rule which must have made ananicy unable to work. But it's been fixed since +1.0.2

**Comment by Shendisx** [comment]
Can you share your `systemctl status ananicy-cpp.service` output?

**Comment by vnepogodin** [comment]
> I noticed that at startup the ananicy-rules are not applied.
> 
> The ananicy-cpp.service is running, restarting the service can trigger its application, otherwise,
> 
> the rules are applied when i start a specific application, i noticed it with firefox.
> 
> I'm not sure if it's an ananicy-cpp bug or the rules.
> bug.mp4

from your video I see that it is applying rules correctly. ananicy is applying rules when it's started and when you launch processes or the processes create forks(child processes). so it is working correctly

**Comment by Ssdj3nt** [comment]
> Can you share your `systemctl status ananicy-cpp.service` output?

[ssdj3nt@archlinux ~]$ systemctl status ananicy-cpp.service
● ananicy-cpp.service - Ananicy-Cpp - ANother Auto NICe daemon in C++
     Loaded: loaded (/usr/lib/systemd/system/ananicy-cpp.service; enabled; preset: disabled)
     Active: active (running) since Sun 2024-12-29 14:11:59 CET; 14s ago
 Invocation: 485a4acb6fe044118389218bff1104cd
   Main PID: 669 (ananicy-cpp)
      Tasks: 1 (limit: 38149)
     Memory: 17.4M (high: 16M, max: 64M, available: 0B, peak: 17.6M, swap: 272K, swap peak: 272K)
        CPU: 1.007s
     CGroup: /system.slice/ananicy-cpp.service
             └─669 /usr/bin/ananicy-cpp start

dic 29 14:11:59 archlinux systemd[1]: Started Ananicy-Cpp - ANother Auto NICe daemon in C++.

**Comment by Ssdj3nt** [comment]
> > I noticed that at startup the ananicy-rules are not applied.
> > The ananicy-cpp.service is running, restarting the service can trigger its application, otherwise,
> > the rules are applied when i start a specific application, i noticed it with firefox.
> > I'm not sure if it's an ananicy-cpp bug or the rules.
> > bug.mp4
> 
> from your video I see that it is applying rules correctly. ananicy is applying rules when it's started and when you launch processes or the processes create forks(child processes). so it is working correctly

Rules for discord and other applications are also included, but they are not applied, except for firefox.

**Comment by vnepogodin** [comment]
well discord gets applied, but discord doesn't inherit
![image](https://github.com/user-attachments/assets/4caecbf3-2ef1-41b5-a75a-3838203cf13d)

**Comment by Ssdj3nt** [comment]
I can't give an answer but booting the system with the linux kernel instead of the linux-cachyos kernel solved the problem. The rules are now applied at system startup.
