### ISSUE TITLE
Why is htop / btop is BG_CPUIO?

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [CachyOS/ananicy-rules#71]
Those are highly interactive tools, and setting them such a low priority makes them nigh unusable under heavy CPU load.

This is especially ironic, considering they are _the_ tools you would use to renice some CPU-hungry processes if it doesn't happen automatically already.

**Comment by ptr1337** [comment]
https://github.com/CachyOS/ananicy-rules/commit/f139cf4cb32a7fa17121990c486795dcd0b7eb8c
